apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-image-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: private-app
  template:
    metadata:
      labels:
        app: private-app
    spec:
      containers:
      - name: hello-worl-war
        image: pradeepreddyhub/hello-world-war:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: my-registry-secret

  kubectl create secret docker-registry my-registry-secret \
  --docker-server=https://hub.docker.com/repository/docker/pradeepreddyhub/hello-world-war/tags/latest/sha256-3e1c5911ea7689f54521cc8bec545e900a02f2998a2760e6946acb6f38c0a1c0 \
  --docker-username=pradeepreddyhub \
  --docker-password=Pradeep*90 \
  --docker-email=pradeep.it.reddy@gmail.com
