-------------------cat nginx-pod.yaml--------------------------------------------------
apiVersion: apps/v1                   # API version for ReplicaSet
kind: ReplicaSet                      # This defines a ReplicaSet resource
metadata:
  name: nginx-replica-set           # Name of the ReplicaSet
  namespace: default                  # Namespace where it will be created
spec:
  replicas: 1                      # Number of Pod replicas to maintain
  selector: 
    matchLabels:
      my-pod: my-nginx            # Selector to match the Pods controlled by this ReplicaSet
  template:                           # Template for the Pods to be created
    metadata:
      labels:
        my-pod: my-nginx            # Label that must match the selector
    spec:
      containers:
        - name: nginx               # Container name
          image: nginx:latest  # Jenkins image from Docker Hub

-----------------------cat nginx-service.yaml-----------------------------------------
apiVersion: v1                        # API version for Service
kind: Service                         # This defines a Service resource
metadata:
  name: ngnix-nodeport              # Name of the Service
spec:
  type: NodePort                      # Makes the Service accessible from outside the cluster
  selector:
    my-pod: my-nginx               # Selects Pods with this label (linked to ReplicaSet)
  ports:
    - protocol: TCP                   # Network protocol
      port: 80                      # Service port inside the cluster
      targetPort: 80                # Port on the Pod/container
      nodePort: 30009                 # Port on the Node (for external access)
