apiVersion: v1
kind: Pod
metadata:
  name: python-k8s-client
spec:
  serviceAccountName: python-client-sa
  containers:
  - name: python
    image: python:3.10
    command: ["sleep","3600"]
  restartPolicy: Never
