apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-python-client
  namespace: dev
spec:
  serviceAccountName: ubuntu-python-sa
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["sleep","3600"]
  restartPolicy: Never
